### ISSUE TITLE
How can i use without module bundler

### ISSUE THREAD

**Issue by drnkwati** [xpl/es7-object-polyfill#1]
Is there a simpler script for web browsers without the need for require or module bundlers

**Comment by xpl** [comment]
@drnkwati I've made a browser build for you. Try this:

https://github.com/xpl/es7-object-polyfill/blob/master/build/es7-object-polyfill.browser.js

It is also available from Unpkg CDN:

```html
<script src="https://unpkg.com/es7-object-polyfill"></script>
```
