### ISSUE TITLE
Propose] would you like to change arrow function to normal function?

### ISSUE THREAD

**Issue by Azurewarth0920** [xpl/es7-object-polyfill#3]
https://github.com/xpl/es7-object-polyfill/blob/4b3813212bb0751dff31b6e9dc471cc411e77e0f/es7-object-polyfill.js#L11

↑ in order to use polyfill in IE11, I have to transpile this polyfill into ES5 but due to #2 I cannot.
So can I write a pull request to change the arrow function to normal function or just compile it into ES5?

**Comment by xpl** [comment]
@KaraMisoRamen I've fixed the issue just recently, plz check the new module version (1.0.0)

**Comment by Azurewarth0920** [comment]
@xpl thanks a lot!
