### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by BMillsVT** [xpl/es7-object-polyfill#5]
Would you consider adding a permissive license - like the MIT License - to this library? 

My company prefers that we don't use software provided under the Unlicensed.  Other have argued (and our lawyers at least agree enough to make it off limits) that the Unlicense causes more issues than it solves.

For [example](http://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense):

> It's not global. It doesn't make sense outside of a commonwealth ecosystem, is explicitly illegal in some places (Germany), and of unclear legality in others (Australia)
> 
> It's inconsistent. Some of the warranty terms cannot, logically, co-exist, given the current legal ecosystem, as written, with the licensing terms.
> 
> Its applicability is unpredictable. The license is short, clearly expressing intent, at the cost of not carefully addressing common license, copy-right and warranty issues. It leaves a lot of leeway interpretation - meaning that, in the US, it will take a few trials before you can reliably know when the license is applicable, and how.

**Comment by xpl** [comment]
@BMillsVT Done. Changed to MIT in 2e2d4d8349b90cd800d9b34e1005fa7a46333f66

However, I'd argue that MIT is actually _less permissive_, because it obliges to include the license text in copies and derivative works, i.e. it works like a self-replicating virus :)

> The above copyright notice and this permission notice *shall be* included <...>
